<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFUqm1ud\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFUqm1ud/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFUqm1ud.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFUqm1ud\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFUqm1ud\App_KernelDevDebugContainer([
    'container.build_hash' => 'FUqm1ud',
    'container.build_id' => 'f6e7f815',
    'container.build_time' => 1614192864,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFUqm1ud');
